server:
  port: 9090

spring:
  profiles:
    active: test
  security:
    oauth2:
      client:
        registration:
          website:
            client-id: client
            client-secret: client
            client-name: testClient
            provider: website
            scope: message:read, message:write
            redirect-uri: http://localhost:9090/login/oauth2/code/website
            client-authentication-method: basic
            authorization-grant-type: authorization_code
        provider:
          website:
            authorization-uri: http://localhost:9093/uaa/oauth/authorize
            token-uri: http://localhost:9093/uaa/oauth/token
            user-info-uri: http://localhost:9093/uaa/me
            jwk-set-uri: http://localhost:9093/uaa/.well-known/jwks.json
            user-name-attribute: name
  cloud:
    gateway:
      routes:
      - id: content
        uri: http://127.0.0.1:9092/content
        predicates:
        - Path=/api/content/**
        filters:
        - RewritePath=/api/(?<segment>.*), /$\{segment}

---
spring:
  profiles: prod

logging:
  config: classpath:log4j2-spring-prod.xml

---
spring:
  profiles: test

logging:
  config: classpath:log4j2-spring-test.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"

