server:
  port: 8090
  address: 127.0.0.1

spring:
#  redis:
#    host: localhost
#    port: 6379
#    password: #password
  session:
    store-type: redis
    timeout: 86400

management:
  endpoints:
    web:
      exposure:
        include: "*"
