language: java

jdk:
  - openjdk11

cache:
  directories:
    - $HOME/.m2

services:
  - cassandra

addons:
  hosts:
    - cassandra
    - www.flowant.org
    - gateway.flowant.org
    - backend.flowant.org
    - auth.flowant.org

script: "mvn clean test"