version: "3.7"

services:

  cassandra:
    image: cassandra:latest
    ports:
      - "9042"
      - "7000"
    volumes:
      - /home/flowant/cassandra_data:/var/lib/cassandra
    networks:
      - maven-build

  maven-build:
    build:
      context: .
    env_file:
      - /home/flowant/work/env_file.txt
    volumes:
      - .:/usr/share/website
    networks:
      - maven-build

networks:
  maven-build:
