server:
  port: 9093
  address: 127.0.0.1

spring:
  profiles:
    active: prod

management:
  endpoints:
    web:
      exposure:
        include: "*"

dev:
  user: user
  userPassword: user
  client: client
  clientPassword: client
  admin: client
  adminPassword: client

---
spring:
  profiles: prod

logging:
  config: classpath:log4j2-spring-prod.xml

---
spring:
  profiles: test

logging:
  config: classpath:log4j2-spring-test.xml
