server:
  port: 9093
  address: 127.0.0.1

spring:
  profiles:
    active: test
  data:
    cassandra:
      contactPoints: 127.0.0.1
      port: 9042
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            client-name: Google
            provider: google
            scope: openid email
            redirect-uri: http://localhost:8080
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            client-name: Facebook
            provider: facebook
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            client-name: Github
            provider: github
            scope: user

website:
  cql-create-keyspace: "CREATE KEYSPACE IF NOT EXISTS %s WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };"
  oauth2-server:
    clientId: ${OAUTH2_CLIENT_ID}
    clientSecret: ${OAUTH2_CLIENT_PASSWORD}
    authorizedGrantTypes:
      - password
      - authorization_code
      - refresh_token
      - client_credentials
    authorities:
      - auth
    accessTokenValiditySeconds: 3600
    refreshTokenValiditySeconds: 3600
    scopes:
      - message:read
      - message:write
    autoApproveScopes:
      - read
      - write
    autoApprove: true
    registeredRedirectUris: "http://localhost:9093/"
    resourceIds: id1, id2
    additionalInformation:
      org: flowant
  keystore:
    path: classpath:keystore/keystore.jks
    alias: website_keystore
    password: ${OAUTH2_KEYSTORE_STOREPASS}

management:
  endpoints:
    web:
      exposure:
        include: "*"

---
spring:
  profiles: prod
  data:
    cassandra:
      keyspace-name: backend_prod
      schema-action: CREATE_IF_NOT_EXISTS

logging:
  config: classpath:log4j2-spring-prod.xml

---
spring:
  profiles: test
  data:
    cassandra:
      keyspace-name: backend_test
      schema-action: recreate # recreate is slow because of doing recreating
#      schema-action: CREATE_IF_NOT_EXISTS

logging:
  config: classpath:log4j2-spring-test.xml
