server:
  port: 9093
  address: 127.0.0.1

spring:
  profiles:
    active: prod
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            client-name: Google
            provider: google
            scope: openid email
            redirect-uri: http://localhost:8080
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            client-name: Facebook
            provider: facebook
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            client-name: Github
            provider: github
            scope: user

keystore:
    path: classpath:keystore/keystore.jks
    alias: website_keystore
    password: ${OAUTH2_KEYSTORE_STOREPASS}

management:
  endpoints:
    web:
      exposure:
        include: "*"

dev:
  user: user
  userPassword: user
  client: client
  clientPassword: client
  admin: client
  adminPassword: client

---
spring:
  profiles: prod

logging:
  config: classpath:log4j2-spring-prod.xml

---
spring:
  profiles: test

logging:
  config: classpath:log4j2-spring-test.xml
