server:
  port: 9090
  address: 127.0.0.1

spring:
  cloud:
    gateway:
      routes:
      - id: content
        uri: http://127.0.0.1:9092/content
        predicates:
        - Path=/content/**

      - id: frontend
        uri: http://127.0.0.1:9091
        predicates:
        - Path=/frontend/**
        filters:
        - RewritePath=/frontend/(?<segment>.*), /$\{segment}

security:
  oauth2:
    client:
      client-id: client
      client-secret: client
      access-token-uri: http://localhost:9093/oauth/token
      user-authorization-uri: http://localhost:9093/oauth/authorize

management:
  endpoints:
    web:
      exposure:
        include: "*"
