server:
  port: 9091

spring:
  profiles:
    active: test
  cloud:
    gateway:
      routes:
      - id: content
        uri: http://127.0.0.1:9092/content
        predicates:
        - Path=/api/content/**
        filters:
        - RewritePath=/api/(?<segment>.*), /$\{segment}
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:9090"
            allowedMethods: GET, POST, PUT, DELETE

---
spring:
  profiles: prod

logging:
  config: classpath:log4j2-spring-prod.xml

---
spring:
  profiles: test

logging:
  config: classpath:log4j2-spring-test.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"
