server:
  port: 9091

spring:
  profiles:
    active: test
  cloud:
    gateway:
      routes:
      - id: website
        uri: http://127.0.0.1:9092/website
        predicates:
        - Path=/api/website/**
        filters:
        - RewritePath=/api/(?<segment>.*), /$\{segment}

      - id: subitem
        uri: http://127.0.0.1:9092/subitem
        predicates:
        - Path=/api/subitem/**
        filters:
        - RewritePath=/api/(?<segment>.*), /$\{segment}

      - id: search
        uri: http://127.0.0.1:9092/search
        predicates:
        - Path=/api/search/**
        filters:
        - RewritePath=/api/(?<segment>.*), /$\{segment}

      - id: content
        uri: http://127.0.0.1:9092/content
        predicates:
        - Path=/api/content/**
        filters:
        - RewritePath=/api/(?<segment>.*), /$\{segment}

      - id: review
        uri: http://127.0.0.1:9092/review
        predicates:
        - Path=/api/review/**
        filters:
        - RewritePath=/api/(?<segment>.*), /$\{segment}

      - id: reply
        uri: http://127.0.0.1:9092/reply
        predicates:
        - Path=/api/reply/**
        filters:
        - RewritePath=/api/(?<segment>.*), /$\{segment}

      - id: content_rpt
        uri: http://127.0.0.1:9092/content_rpt
        predicates:
        - Path=/api/content_rpt/**
        filters:
        - RewritePath=/api/(?<segment>.*), /$\{segment}

      - id: review_rpt
        uri: http://127.0.0.1:9092/review_rpt
        predicates:
        - Path=/api/review_rpt/**
        filters:
        - RewritePath=/api/(?<segment>.*), /$\{segment}

      - id: reply_rpt
        uri: http://127.0.0.1:9092/reply_rpt
        predicates:
        - Path=/api/reply_rpt/**
        filters:
        - RewritePath=/api/(?<segment>.*), /$\{segment}

      - id: files
        uri: http://127.0.0.1:9092/files
        predicates:
        - Path=/api/files/**
        filters:
        - RewritePath=/api/(?<segment>.*), /$\{segment}

      - id: message
        uri: http://127.0.0.1:9092/message
        predicates:
        - Path=/api/message/**
        filters:
        - RewritePath=/api/(?<segment>.*), /$\{segment}

      - id: notification
        uri: http://127.0.0.1:9092/notification
        predicates:
        - Path=/api/notification/**
        filters:
        - RewritePath=/api/(?<segment>.*), /$\{segment}

      - id: relation
        uri: http://127.0.0.1:9092/relation
        predicates:
        - Path=/api/relation/**
        filters:
        - RewritePath=/api/(?<segment>.*), /$\{segment}

      - id: user
        uri: http://127.0.0.1:9092/user
        predicates:
        - Path=/api/user/**
        filters:
        - RewritePath=/api/(?<segment>.*), /$\{segment}

website:
  cors:
    allowedOrigins: "http://localhost:9090"

---
spring:
  profiles: prod

logging:
  config: classpath:log4j2-spring-prod.xml

---
spring:
  profiles: test

logging:
  config: classpath:log4j2-spring-test.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"
