server:
  port: 9091
  address: 127.0.0.1

spring:
  profiles:
    active: test
  cloud:
    gateway:
      routes:
      - id: content
        uri: http://127.0.0.1:9092/content
        predicates:
        - Path=/content/**
      - id: logout
        uri: http://127.0.0.1:9093/logout
        predicates:
        - Path=/logout

---
spring:
  profiles: prod

logging:
  config: classpath:log4j2-spring-prod.xml

---
spring:
  profiles: test

logging:
  config: classpath:log4j2-spring-test.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"
