server:
  port: 443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: keystore/ssl_certificate.p12
    key-store-password: ${SSL_KEYSTORE_STOREPASS}
    key-alias: website_ssl

spring:
  profiles:
    active: test
  cloud:
    gateway:
      routes:
      - id: website
        uri: https://backend.flowant.org/website
        predicates:
        - Path=/api/website/**
        filters:
        - RewritePath=/api/(?<segment>.*), /$\{segment}

      - id: subitem
        uri: https://backend.flowant.org/subitem
        predicates:
        - Path=/api/subitem/**
        filters:
        - RewritePath=/api/(?<segment>.*), /$\{segment}

      - id: search
        uri: https://backend.flowant.org/search
        predicates:
        - Path=/api/search/**
        filters:
        - RewritePath=/api/(?<segment>.*), /$\{segment}

      - id: content
        uri: https://backend.flowant.org/content
        predicates:
        - Path=/api/content/**
        filters:
        - RewritePath=/api/(?<segment>.*), /$\{segment}

      - id: review
        uri: https://backend.flowant.org/review
        predicates:
        - Path=/api/review/**
        filters:
        - RewritePath=/api/(?<segment>.*), /$\{segment}

      - id: reply
        uri: https://backend.flowant.org/reply
        predicates:
        - Path=/api/reply/**
        filters:
        - RewritePath=/api/(?<segment>.*), /$\{segment}

      - id: content_rpt
        uri: https://backend.flowant.org/content_rpt
        predicates:
        - Path=/api/content_rpt/**
        filters:
        - RewritePath=/api/(?<segment>.*), /$\{segment}

      - id: review_rpt
        uri: https://backend.flowant.org/review_rpt
        predicates:
        - Path=/api/review_rpt/**
        filters:
        - RewritePath=/api/(?<segment>.*), /$\{segment}

      - id: reply_rpt
        uri: https://backend.flowant.org/reply_rpt
        predicates:
        - Path=/api/reply_rpt/**
        filters:
        - RewritePath=/api/(?<segment>.*), /$\{segment}

      - id: files
        uri: https://backend.flowant.org/files
        predicates:
        - Path=/api/files/**
        filters:
        - RewritePath=/api/(?<segment>.*), /$\{segment}

      - id: message
        uri: https://backend.flowant.org/message
        predicates:
        - Path=/api/message/**
        filters:
        - RewritePath=/api/(?<segment>.*), /$\{segment}

      - id: notification
        uri: https://backend.flowant.org/notification
        predicates:
        - Path=/api/notification/**
        filters:
        - RewritePath=/api/(?<segment>.*), /$\{segment}

      - id: relation
        uri: https://backend.flowant.org/relation
        predicates:
        - Path=/api/relation/**
        filters:
        - RewritePath=/api/(?<segment>.*), /$\{segment}

      - id: user
        uri: https://backend.flowant.org/user
        predicates:
        - Path=/api/user/**
        filters:
        - RewritePath=/api/(?<segment>.*), /$\{segment}

      - id: oauth
        uri: https://auth.flowant.org/uaa/oauth/token
        predicates:
        - Path=/api/oauth/token/**
        filters:
        - RewritePath=/api/(?<segment>.*), /uaa/$\{segment}

website:
  cors:
    allowedOrigins: "https://www.flowant.org"

---
spring:
  profiles: prod

logging:
  config: classpath:log4j2-spring-prod.xml

---
spring:
  profiles: test

logging:
  config: classpath:log4j2-spring-test.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"
