server:
  port: 8080
  address: 127.0.0.1

spring:
#  redis:
#    host: localhost
#    port: 6379
#    password: #password
  session:
    store-type: redis
    timeout: 86400
#    redis:
#      flush-mode=on-save # Sessions flush mode.
#      namespace=spring:session # Namespace for keys used to store sessions.
  cloud:
    gateway:
      routes:
      - id: frontend
        uri: http://127.0.0.1:8090/frontend
        predicates:
        - Path=/frontend/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
