spring:
  application:
    name: registry
  profiles:
    active: prod
  security:
    basic:
      enabled: true
    user:
      name: ${EUREKA_ID}
      password: ${EUREKA_PASSWORD}

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

---
spring:
  profiles: prod

logging:
  config: classpath:log4j2-spring-prod.xml

---
spring:
  profiles: test

logging:
  config: classpath:log4j2-spring-test.xml
    