spring:
  profiles:
    active: test
  data:
    cassandra:
      contactPoints: 127.0.0.1
      port: 9042

website:
  cassandra:
    cqlCreateKeySpace: "CREATE KEYSPACE IF NOT EXISTS %s WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };"

---
spring:
  profiles: prod
  data:
    cassandra:
      keyspace-name: backend_prod
      schema-action: CREATE_IF_NOT_EXISTS

logging:
  config: classpath:log4j2-spring-prod.xml

---
spring:
  profiles: test
  data:
    cassandra:
      keyspace-name: backend_test
      schema-action: CREATE_IF_NOT_EXISTS
#      schema-action: recreate # should be recreated only if models are changed.

logging:
  config: classpath:log4j2-spring-test.xml

