spring:
  profiles:
    active: prod
  data:
    cassandra:
      contactPoints: 127.0.0.1
      port: 9042
      cql-create-keyspace: "CREATE KEYSPACE IF NOT EXISTS %s WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };"

---
spring:
  profiles: prod
  data:
    cassandra:
      keyspace-name: backend_prod
      schema-action: CREATE_IF_NOT_EXISTS

logging:
  config: classpath:log4j2-spring-prod.xml

---
spring:
  profiles: test
  data:
    cassandra:
      keyspace-name: backend_test
#      schema-action: CREATE_IF_NOT_EXISTS
      schema-action: recreate # recreate is slow because of doing recreating

logging:
  config: classpath:log4j2-spring-test.xml

